# Generated by Django 5.2.1 on 2025-05-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('image1', models.ImageField(null=True, upload_to='')),
                ('image2', models.ImageField(null=True, upload_to='')),
                ('image3', models.ImageField(null=True, upload_to='')),
                ('image4', models.ImageField(null=True, upload_to='')),
                ('image5', models.ImageField(null=True, upload_to='')),
                ('size1', models.IntegerField(default=0)),
                ('size2', models.IntegerField(default=0)),
                ('size3', models.IntegerField(default=0)),
                ('size4', models.IntegerField(default=0)),
                ('size5', models.IntegerField(default=0)),
                ('width1', models.CharField(max_length=255)),
                ('width2', models.CharField(max_length=255)),
                ('width3', models.CharField(max_length=255)),
                ('width4', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pdetail1', models.CharField(max_length=255)),
                ('pdetail2', models.CharField(max_length=255)),
                ('pdetail3', models.CharField(max_length=255)),
                ('pdetail4', models.CharField(max_length=255)),
                ('pdetail5', models.CharField(max_length=255)),
                ('category', models.ManyToManyField(to='home.category')),
                ('type', models.ManyToManyField(to='home.type')),
            ],
        ),
    ]
