# Generated by Django 5.2.1 on 2025-06-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_type_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('pid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('size1', models.IntegerField(default=0)),
                ('size2', models.IntegerField(default=0)),
                ('size3', models.IntegerField(default=0)),
                ('size4', models.IntegerField(default=0)),
                ('size5', models.IntegerField(default=0)),
                ('width1', models.CharField(max_length=255)),
                ('width2', models.CharField(max_length=255)),
                ('width3', models.CharField(max_length=255)),
                ('width4', models.CharField(max_length=255)),
                ('category', models.ManyToManyField(to='home.category')),
            ],
        ),
    ]
