# Generated by Django 5.2.1 on 2025-06-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
    ]
