# Generated by Django 5.2.1 on 2025-06-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('bid', models.BigAutoField(primary_key=True, serialize=False)),
                ('oid', models.IntegerField(default=0)),
                ('cid', models.IntegerField(default=0)),
                ('uid', models.IntegerField(default=0)),
                ('pid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('price', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payid', models.BigAutoField(primary_key=True, serialize=False)),
                ('oid', models.IntegerField(default=0)),
                ('uid', models.IntegerField(default=0)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=255)),
                ('cname', models.CharField(max_length=255)),
                ('expdate', models.CharField(max_length=255)),
                ('cvv', models.IntegerField(default=0)),
                ('cardno', models.CharField(max_length=255)),
                ('billing', models.ManyToManyField(to='home.billing')),
            ],
        ),
    ]
