# Generated by Django 5.2.1 on 2025-06-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_billing_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
