# Generated by Django 5.2.1 on 2025-06-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_billing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
