# Generated by Django 5.2.3 on 2025-06-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_billing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='billing',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
