# Generated by Django 5.2.3 on 2025-06-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_payment_billing_delete_cart_delete_billing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('bid', models.BigAutoField(primary_key=True, serialize=False)),
                ('oid', models.IntegerField(default=0)),
                ('cid', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=255)),
                ('pid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('size1', models.IntegerField(default=0)),
                ('size2', models.IntegerField(default=0)),
                ('size3', models.IntegerField(default=0)),
                ('size4', models.IntegerField(default=0)),
                ('size5', models.IntegerField(default=0)),
                ('width1', models.CharField(max_length=255)),
                ('width2', models.CharField(max_length=255)),
                ('width3', models.CharField(max_length=255)),
                ('width4', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payid', models.BigAutoField(primary_key=True, serialize=False)),
                ('oid', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=255)),
                ('cname', models.CharField(max_length=255)),
                ('expdate', models.CharField(max_length=255)),
                ('cvv', models.IntegerField(default=0)),
                ('cardno', models.CharField(max_length=255)),
                ('billing', models.ManyToManyField(to='home.billing')),
            ],
        ),
    ]
