# Generated by Django 5.2.1 on 2025-06-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
