# Generated by Django 5.2.2 on 2025-06-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_billing_cart_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='oid',
            field=models.IntegerField(default=0),
        ),
    ]
