# Generated by Django 5.2.1 on 2025-06-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='billing',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
