# Generated by Django 5.2.2 on 2025-06-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_cart_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='oid',
        ),
    ]
