# Generated by Django 5.2.1 on 2025-06-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_billing_cart_payment'),
        ('home', '0013_remove_cart_oid'),
    ]

    operations = [
    ]
