# Generated by Django 5.2.1 on 2025-06-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_0013_billing_cart_payment_0013_remove_cart_oid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
